FROM centos:8
RUN  yum update -y && \
  yum install -y \
    git-2.27.0-1.el8.x86_64 python36-3.6.8-2.module_el8.4.0+790+083e3d81.x86_64 python3-pip-9.0.3-19.el8.noarch python3-flask.noarch python3-requests
